### ISSUE TITLE
Example 2 Triangle NDK OpenGL ES API with no current context

### ISSUE THREAD

**Issue by stericardo** [danginsburg/opengles3-book#20]
I buy the book. The example 2 of the triangle, I do steps of chapter 16 for build with Android NDK.

I have android 4.4.2.
NDK: android-ndk-r10e

ENVIRONMENT VARIABLES WITH CYGWIN:

export JAVA_HOME="/cygdrive/c/Program Files/Java/jdk1.7.0_45"
export ANDROID_SDK=/cygdrive/c/Users/steven.mendez/sdk
export ANDROID_NDK=/cygdrive/c/Users/steven.mendez/Documents/Development/Android/android-ndk-r10e
export ANT=/cygdrive/c/Users/steven.mendez/Documents/Development/apache-ant-1.9.2\bin
export PATH=$PATH:${ANDROID_NDK}
export PATH=$PATH:${ANT}
export PATH=$PATH:${ANDROID_SDK}/tools
export PATH=$PATH:${ANDROID_SDK}/platform-tools.

After install(adb install -r bin/NativeActivity-debug.apk), I do test on my mobile, but the error on adb is:

E/cutils  (  177): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(11766): Failed to ensure directory: /storage/sdcard1/Android/obb/com.openglesbook.HelloTriangle
E/cutils  (  177): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl(11766): Failed to ensure directory: /storage/sdcard1/Android/data/com.openglesbook.HelloTriangle/files
W/linker  (11766): library "libmaliinstr.so" not found
W/linker  (11766): error:
E/libEGL  (11766): call to OpenGL ES API with no current context (logged once per thread)
E/libEGL  (11766): call to OpenGL ES API with no current context (logged once per thread)
E/libEGL  (11766): call to OpenGL ES API with no current context (logged once per thread)
I/AudioFlinger(11766): LppThread::~LppThread()
I/ActivityManager(  603): Displayed com.openglesbook.HelloTriangle/android.app.NativeActivity: +162ms
I/CpuGovernorPolicy(  868): cpu draw 
W/Binder  (  805): Caught a RuntimeException from the binder stub implementation.
W/Binder  (  805): java.lang.NullPointerException
W/Binder  (  805):      at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  (  805):      at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  (  805):      at android.os.Binder.execTransact(Binder.java:404)
W/Binder  (  805):      at dalvik.system.NativeStart.run(Native Method)
W/System.err(  805): java.lang.NullPointerException
W/System.err(  805):    at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/System.err(  805):    at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/System.err(  805):    at android.os.Binder.execTransact(Binder.java:404)
W/System.err(  805):    at dalvik.system.NativeStart.run(Native Method)
I/CpuGovernorPolicy(  868): gpu draw 
I/DHCPCD  ( 2214): wlan0: Router Advertisement from fe80::920d:cbff:fe36:d111
I/DHCPCD  ( 2214): wlan0: fe80::920d:cbff:fe36:d111: expired Router Advertisement

**Comment by jamesfolk** [comment]
What is your question?

**Comment by stericardo** [comment]
Why is present this error ?.

 it should  work fine ?

**Comment by stericardo** [comment]
Hi, I do steps ¨BUILD FOR UBUNTU LINUX¨ chapter 16, but on Windows 7 with cywing, all is working fine.

I think so my problem is that my phone, it have android 4.4.2 but look that not support OpenGL ES 3.0, only OpenGl ES 2.0. 

I'm not sure if the error with NDK build is for this reason.

**Comment by stericardo** [comment]
Only I have one last question, why do work fine on my windows 7 ? If Windows 7 support until OpenGL 4.0. I understant that OpenGL ES 3.0 is based on OpenGL 4.3.

Is Cygwin the emulator that achieved this ?

**Comment by stericardo** [comment]
I known that my windows 7 support OpenGL 4.0, thanks to OpenGL Extensions Viewer 4.1.2, my renderer is Intel(R) hd Graphics 4000
